# Generated by Django 6.0 on 2026-01-10 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_elements_element_rename_roles_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='role_name',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='role_permission',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_role',
        ),
        migrations.AddField(
            model_name='permission',
            name='create_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='delete_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='element_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.element'),
        ),
        migrations.AddField(
            model_name='permission',
            name='read_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.role'),
        ),
        migrations.AddField(
            model_name='permission',
            name='update_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=255),
        ),
    ]
