# Generated by Django 6.0 on 2026-01-12 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_permission_role_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role_id',
            field=models.ForeignKey(default=4, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.role'),
        ),
    ]
