# Generated by Django 6.0 on 2026-01-12 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_user_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='element_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.element'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='account.role'),
        ),
    ]
