# Generated by Django 6.0 on 2026-01-13 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_permission_element_id_alter_permission_role_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_role_id',
        ),
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.ForeignKey(db_column='role_id', default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='account.role'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='element_id',
            field=models.ForeignKey(db_column='element_id', on_delete=django.db.models.deletion.DO_NOTHING, to='account.element'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='role_id',
            field=models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.DO_NOTHING, to='account.role'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.UUIDField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.user')),
            ],
        ),
    ]
