# Generated by Django 6.0 on 2026-01-13 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_user_user_role_id_user_role_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='account.user'),
        ),
    ]
