# Generated by Django 6.0 on 2026-01-13 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_session_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='expires',
            new_name='expires_at',
        ),
    ]
